# GitHub Pages Configuration for Trump Pardons Database

# Site settings
title: "Trump Pardons Database"
description: "Comprehensive database of presidential pardons and commutations across both Trump presidencies with enhanced mobile interface and demographics analysis"
url: "https://codeddarkness.github.io"
baseurl: "/taco_pardons"

# GitHub Pages settings
plugins:
  - jekyll-redirect-from

# Include files that GitHub Pages should serve
include:
  - trump_pardons_database.html
  - trump_pardons_csv.txt
  - trump_pardons_first_term_csv.txt
  - screenshots/
  - index.html

# Exclude development files
exclude:
  - patches/
  - backup_*/
  - "*.bak"
  - "*.backup"
  - add_first_term_patch*.sh
  - deploy_*.sh
  - merge_*.sh
  - update_*.sh
  - dir_status.txt
  - paste.txt

# Markdown settings
markdown: kramdown
highlighter: rouge

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Performance settings
sass:
  style: compressed

# SEO settings
author: Raymond Scheel
version: "2.2"
last_updated: "2025-06-09"
